export const SUPABASE_CONFIG = {
  GARMENTS_TABLE: process.env.NEXT_PUBLIC_SUPABASE_GARMENTS_TABLE!,
  OUTFITS_TABLE: process.env.NEXT_PUBLIC_SUPABASE_OUTFITS_TABLE!,
  OFFICE_DAYS_TABLE: process.env.NEXT_PUBLIC_SUPABASE_OFFICE_DAYS_TABLE!,
  FEEDBACK_TABLE: process.env.NEXT_PUBLIC_SUPABASE_FEEDBACK_TABLE!,
  STORAGE_BUCKET: process.env.NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET!,
};
